### ISSUE TITLE
AttributeError: 'IsoAccessor' object has no attribute 'realpath'

### ISSUE THREAD

**Issue by einstein95** [barneygale/pathlab#3]
While attempting to replicate the example on https://pathlab.readthedocs.io/en/latest/basics.html#iso-images, I got this error (Python 3.10.7, Arch Linux)
```
>>> root = disc.IsoPath('/')
>>> readme = root / 'readme.txt'
>>> readme.exists()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.10/pathlib.py", line 1290, in exists
    self.stat()
  File "/usr/lib/python3.10/pathlib.py", line 1097, in stat
    return self._accessor.stat(self, follow_symlinks=follow_symlinks)
  File "/home/user/.local/lib/python3.10/site-packages/pathlab/iso.py", line 308, in stat
    path = path.resolve()
  File "/usr/lib/python3.10/pathlib.py", line 1077, in resolve
    s = self._accessor.realpath(self, strict=strict)
AttributeError: 'IsoAccessor' object has no attribute 'realpath'
```

**Comment by niemasd** [comment]
I'm getting this error as well in Python 3.10.12. Any solutions?
